[project]
name = "iflow-mcp_rafaelcartenet-databricks"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "databricks-sdk==0.77.0",
    "python-dotenv>=1.2.1",
]
[project.scripts]
databricks = "iflow_mcp_rafaelcartenet_databricks.main:main"

[tool.setuptools]
packages = ["iflow_mcp_rafaelcartenet_databricks"]

[tool.setuptools.package-data]
"iflow_mcp_rafaelcartenet_databricks" = ["assets/*"]